import test from 'node:test';
import assert from 'node:assert/strict';
import { createMachineKernel } from '../src/machine-kernel.mjs';
import { createInMemoryPersistence } from './support/in-memory-persistence.mjs';
import { createExperimentAdapter } from '../src/logic-adapters.mjs';
import { runLogicMachine } from '../src/logic-machine.mjs';
import { EXECUTION_STATE, RETURN_STATE, SUBJECT_ASSESSMENT } from '../src/machine-contract.mjs';
import { createDurableStore } from '../src/durable-store.mjs';
import { createInMemoryDurableDriver } from './support/in-memory-durable-driver.mjs';
import { createLogicRegistry } from '../src/logic-registry.mjs';

function work(runId = 'RUN-LOGIC-1') { return { runId, workId: `WORK-${runId}`, machineId: 'LOGIC-MACHINE', machineVersion: '0.1.0', domain: 'LOGIC', ingress: { systemId: 'METROPOLIS', surfaceType: 'STATION', surfaceId: 'METROPOLIS-STATION' }, destination: { systemId: 'FACTORY', surfaceType: 'OWNER', surfaceId: 'LOGIC', ownerDomain: 'LOGIC' }, transportRef: { kind: 'RAIL', linkId: 'METRO-FACTORY', trustBoundaryRef: 'TB-METRO-FACTORY' }, requestedBy: { actorId: 'GO', authorityRef: 'AUTH-LOGIC', requestedAt: '2026-10-05T00:00:00Z' }, subject: { subjectId: `AGENT-${runId}`, subjectType: 'LOGIC_AGENT', ownerSystem: 'LOGIC', lifecycleAuthorityRef: 'LOGIC-OWNER' } }; }
function kernel() { let n = 0; return createMachineKernel({ persistence: createInMemoryPersistence(), idFactory: () => `ID-${++n}`, clock: (() => { let i = 0; return () => `2026-10-05T00:00:0${i++}Z`; })() }); }
function provider(options = {}) { let evaluated = 0; const step = (name, result = {}) => async () => ({ status: 'PASS', evidenceRef: `evidence://logic/${name}`, ...result }); return { designBench: step('design'), buildBench: step('build'), developmentBench: step('development'), simulate: step('simulation'), runGoldenCases: step('golden'), evaluate: async () => { evaluated += 1; return options.needsRca && evaluated === 1 ? { status: 'NEEDS_RCA', evidenceRef: 'evidence://logic/evaluation-needs-rca' } : { status: 'PASS', evidenceRef: 'evidence://logic/evaluation-pass' }; }, rca: step('rca'), qualifyAgent: step('qualification', { qualificationStatus: 'PENDING_OWNER' }), version: step('version', { versionRef: 'logic://version/1', logicVersion: 'logic-1' }) }; }

test('LOGIC experiment completes without claiming subject qualification', async () => { const result = await runLogicMachine({ kernel: kernel(), adapter: createExperimentAdapter(provider()), work: work() }); assert.equal(result.run.executionState, EXECUTION_STATE.COMPLETE); assert.equal(result.run.returnState, RETURN_STATE.RETURNED); assert.equal(result.run.subjectAssessment.status, SUBJECT_ASSESSMENT.NOT_ASSESSED); assert.equal(result.qualification.qualificationStatus, 'PENDING_OWNER'); });
test('LOGIC evaluation RCA path uses the same kernel lifecycle', async () => { const result = await runLogicMachine({ kernel: kernel(), adapter: createExperimentAdapter(provider({ needsRca: true })), work: work('RUN-RCA') }); assert.equal(result.run.executionState, EXECUTION_STATE.COMPLETE); assert.ok(result.steps.some((item) => item.step === 'RCA')); });
test('Logic Registry stores version, health history and field results through DurableStore', async () => { const registry = createLogicRegistry({ store: createDurableStore({ driver: createInMemoryDurableDriver() }) }); await registry.register({ logicId: 'LOGIC-1', version: 'logic-1', manifest: { target: 'EXPERIMENT' } }); await registry.recordHealth({ logicId: 'LOGIC-1', version: 'logic-1', status: 'READY', evidenceRef: 'evidence://health', observedAt: 'now' }); await registry.recordFieldResult({ logicId: 'LOGIC-1', version: 'logic-1', result: 'PASS', evidenceRef: 'evidence://field', observedAt: 'now' }); assert.equal((await registry.healthHistory('LOGIC-1')).length, 1); assert.equal((await registry.fieldResults('LOGIC-1')).length, 1); });
