import test from 'node:test';
import assert from 'node:assert/strict';
import { createDwarfOperator } from '../src/dwarf-autonomous.mjs';
import { createBilateralRailLink, travelRail } from '../src/rail-link.mjs';
import { createFactoryStationReceiver } from '../src/factory-e2e.mjs';
import { createDurableStore } from '../src/durable-store.mjs';
import { createInMemoryDurableDriver } from './support/in-memory-durable-driver.mjs';

test('DWARF retries a retryable machine failure within the attempt budget', async () => { let calls = 0; const dwarf = createDwarfOperator({ maxAttempts: 2, domainRunners: { CODE: async () => { calls += 1; return calls === 1 ? { retryable: true, run: { executionState: 'UNKNOWN', returnState: 'PENDING' } } : { run: { executionState: 'COMPLETE', returnState: 'RETURNED' } }; } } }); const result = await dwarf.run({ work: { workId: 'WORK-RETRY' }, domain: 'CODE', machineId: 'CODE-MACHINE', authorityRef: 'AUTH' }); assert.equal(result.status, 'RETURNED'); assert.equal(result.lifecycleStatus, 'COMPLETE'); assert.equal(result.attempts, 2); assert.ok(result.events.some((event) => event.phase === 'RECOVER')); });

test('DWARF stops at authority boundary without retrying', async () => { let calls = 0; const dwarf = createDwarfOperator({ maxAttempts: 3, domainRunners: { CODE: async () => { calls += 1; return { authorityBoundary: true, run: { executionState: 'BLOCKED', returnState: 'PENDING' } }; } } }); const result = await dwarf.run({ work: { workId: 'WORK-BLOCKED' }, domain: 'CODE', machineId: 'CODE-MACHINE', authorityRef: 'AUTH' }); assert.equal(result.status, 'BLOCKED'); assert.equal(result.lifecycleStatus, 'BLOCKED'); assert.equal(calls, 1); });

test('Factory Station → bilateral Rail → DWARF → readback is verified', async () => { const link = createBilateralRailLink({ linkId: 'METRO-FACTORY', trustBoundaryRef: 'TB-1', endpoints: [{ endpointId: 'METRO-STATION', systemId: 'METROPOLIS', surfaceId: 'STATION-A' }, { endpointId: 'FACTORY-STATION', systemId: 'FACTORY', surfaceId: 'STATION-B' }] }); const dwarf = createDwarfOperator({ domainRunners: { CODE: async () => ({ run: { executionState: 'COMPLETE', returnState: 'RETURNED' } }) } }); const receiver = createFactoryStationReceiver({ dwarf, store: createDurableStore({ driver: createInMemoryDurableDriver() }) }); const result = await travelRail({ link, envelope: { domain: 'CODE', machineId: 'CODE-MACHINE', authorityRef: 'AUTH', work: { workId: 'WORK-E2E' } }, dispatch: receiver.dispatch, readback: receiver.readback }); assert.equal(result.outcome, 'VERIFIED'); assert.equal(result.readback.dwarfStatus, 'RETURNED'); assert.equal(result.readback.lifecycleStatus, 'COMPLETE'); });

test('DWARF does not promote execution completion when return is still pending', async () => { const dwarf = createDwarfOperator({ domainRunners: { CODE: async () => ({ run: { executionState: 'COMPLETE', returnState: 'PENDING' } }) } }); const result = await dwarf.run({ work: { workId: 'WORK-RETURN-PENDING' }, domain: 'CODE', machineId: 'CODE-MACHINE', authorityRef: 'AUTH' }); assert.equal(result.status, 'UNKNOWN'); assert.equal(result.lifecycleStatus, 'UNKNOWN'); assert.equal(result.result.run.executionState, 'COMPLETE'); assert.equal(result.result.run.returnState, 'PENDING'); });
