import test from 'node:test';
import assert from 'node:assert/strict';
import { createBilateralRailLink, travelRail } from '../src/rail-link.mjs';
import { createPixieOperator } from '../src/pixie-autonomous.mjs';

test('bilateral Rail Link has exactly two Station endpoints and isolates transport failure', async () => { const link = createBilateralRailLink({ linkId: 'METRO-FACTORY', trustBoundaryRef: 'TB-1', endpoints: [{ endpointId: 'METRO-STATION', systemId: 'METROPOLIS', surfaceId: 'STATION-A' }, { endpointId: 'FACTORY-STATION', systemId: 'FACTORY', surfaceId: 'STATION-B' }] }); assert.equal(link.endpoints.length, 2); const failed = await travelRail({ link, envelope: { oathId: 'OATH-1' }, dispatch: async () => { throw Object.assign(new Error('rail down'), { code: 'RAIL_DOWN' }); }, readback: async () => ({ verified: true }) }); assert.equal(failed.outcome, 'FAILED'); assert.equal(failed.failure.stage, 'TRANSPORT'); });

test('Rail → Factory Station → PIXIE routes work without GO/LIGHT step control', async () => { const link = createBilateralRailLink({ linkId: 'METRO-FACTORY', trustBoundaryRef: 'TB-1', endpoints: [{ endpointId: 'METRO-STATION', systemId: 'METROPOLIS', surfaceId: 'STATION-A' }, { endpointId: 'FACTORY-STATION', systemId: 'FACTORY', surfaceId: 'STATION-B' }] }); const calls = []; const pixie = createPixieOperator({ domainRunners: { CODE: async ({ work, actorRef }) => { calls.push({ work, actorRef }); return { run: { executionState: 'COMPLETE', returnState: 'RETURNED' } }; }, VISUAL: async () => ({ run: { executionState: 'COMPLETE', returnState: 'RETURNED' } }), LOGIC: async () => ({ run: { executionState: 'COMPLETE', returnState: 'RETURNED' } }) } }); const received = {}; const traveled = await travelRail({ link, envelope: { oathId: 'OATH-2', workId: 'WORK-2' }, dispatch: async ({ envelope }) => { const result = await pixie.run({ work: { workId: envelope.workId }, domain: 'CODE', machineId: 'CODE-MACHINE', authorityRef: 'AUTH' }); received.result = result; return { accepted: result.status === 'RETURNED', receiptId: 'RECEIPT-2' }; }, readback: async () => ({ verified: true, evidenceRef: 'evidence://rail-2' }) }); assert.equal(traveled.outcome, 'VERIFIED'); assert.equal(received.result.status, 'RETURNED'); assert.equal(calls[0].actorRef, 'PIXIE'); });

test('Bilateral Rail contract rejects one-ended links', () => { assert.throws(() => createBilateralRailLink({ linkId: 'BAD', trustBoundaryRef: 'TB', endpoints: [{ endpointId: 'ONLY', systemId: 'A', surfaceId: 'S' }] }), /EXACTLY_TWO_ENDPOINTS/); });
