import { EXECUTION_STATE, RETURN_STATE } from './machine-contract.mjs';

const executionTransitions = Object.freeze({
  [EXECUTION_STATE.RECEIVED]: new Set([EXECUTION_STATE.INTERPRETED, EXECUTION_STATE.BLOCKED, EXECUTION_STATE.UNKNOWN, EXECUTION_STATE.FAILED]),
  [EXECUTION_STATE.INTERPRETED]: new Set([EXECUTION_STATE.EXECUTING, EXECUTION_STATE.BLOCKED, EXECUTION_STATE.UNKNOWN, EXECUTION_STATE.FAILED]),
  [EXECUTION_STATE.EXECUTING]: new Set([EXECUTION_STATE.VERIFYING, EXECUTION_STATE.BLOCKED, EXECUTION_STATE.UNKNOWN, EXECUTION_STATE.FAILED, EXECUTION_STATE.CANCELLING]),
  [EXECUTION_STATE.VERIFYING]: new Set([EXECUTION_STATE.COMPLETE, EXECUTION_STATE.BLOCKED, EXECUTION_STATE.UNKNOWN, EXECUTION_STATE.FAILED, EXECUTION_STATE.CANCELLING]),
  [EXECUTION_STATE.COMPLETE]: new Set([]),
  [EXECUTION_STATE.BLOCKED]: new Set([EXECUTION_STATE.INTERPRETED, EXECUTION_STATE.UNKNOWN]),
  [EXECUTION_STATE.FAILED]: new Set([EXECUTION_STATE.INTERPRETED, EXECUTION_STATE.UNKNOWN]),
  [EXECUTION_STATE.UNKNOWN]: new Set([EXECUTION_STATE.INTERPRETED, EXECUTION_STATE.VERIFYING]),
  [EXECUTION_STATE.CANCELLING]: new Set([EXECUTION_STATE.CANCELLED, EXECUTION_STATE.UNKNOWN]),
  [EXECUTION_STATE.CANCELLED]: new Set([]),
});

const returnTransitions = Object.freeze({
  [RETURN_STATE.PENDING]: new Set([RETURN_STATE.RETURNED, RETURN_STATE.FAILED, RETURN_STATE.UNKNOWN]),
  [RETURN_STATE.RETURNED]: new Set([]),
  [RETURN_STATE.FAILED]: new Set([RETURN_STATE.PENDING, RETURN_STATE.UNKNOWN]),
  [RETURN_STATE.UNKNOWN]: new Set([RETURN_STATE.PENDING, RETURN_STATE.FAILED]),
});

export function assertExecutionTransition(from, to, patch = {}) {
  if (to === EXECUTION_STATE.CANCELLED) {
    if (from !== EXECUTION_STATE.CANCELLING) throw new Error('CANCELLED_REQUIRES_CANCELLING');
    if (patch.cancellationStatus !== 'VERIFIED' || !Array.isArray(patch.cancellationEvidenceRefs) || patch.cancellationEvidenceRefs.length === 0) {
      throw new Error('CANCELLED_REQUIRES_VERIFIED_STOP');
    }
  }
  if (from === to) return;
  if (!executionTransitions[from]?.has(to)) throw new Error(`INVALID_EXECUTION_TRANSITION:${from}:${to}`);
}

export function assertReturnTransition(from, to) {
  if (from === to) return;
  if (!returnTransitions[from]?.has(to)) throw new Error(`INVALID_RETURN_TRANSITION:${from}:${to}`);
}

export function isExecutionTerminal(state) {
  return state === EXECUTION_STATE.COMPLETE || state === EXECUTION_STATE.CANCELLED;
}

export function isReturnTerminal(state) {
  return state === RETURN_STATE.RETURNED;
}
